/*
 * Locomotive Numbers Validator
 * Copyright (c) 2019.
 */

package com.dfedorov.locomotive;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

/**
 * Default application tests generated by SpringBoot
 */
@RunWith(SpringRunner.class)
@SpringBootTest
public class LocomotiveApplicationTests {

    @Test
    public void contextLoads() {
    }

}
